apiVersion: v1
kind: ConfigMap
metadata:
  name: g-match-config
  namespace: g-match
data:
  # Django settings
  DEBUG: "False"
  ALLOWED_HOSTS: "api.g-match.local,localhost"

  # Database
  DB_NAME: "g_match"
  DB_USER: "django-server"
  DB_HOST: "g-match-mysql"
  DB_PORT: "3306"

  # Redis
  REDIS_HOST: "g-match-redis"
  REDIS_PORT: "6379"

  # Email
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  DEFAULT_FROM_EMAIL: "noreply@g-match.com"
